# Phase 1 of Final Project
## Keith Swartz

```{r}
library(GGally) #create ggcorr and ggpairs plots
library(ggcorrplot)
library(tidyverse)
library(tidymodels)
library(mice) #package for imputation
library(VIM) #visualizing missingness
library(ranger) #for random forests
library(randomForest) #also for random forests
library(caret)

ames_student <- read_csv("~/Downloads/ban-502-ames-classification-summer-2021/ames_student.csv")
```

```{r}
glimpse(ames_student)
summary(ames_student)
```

```{r}
ames = ames_student 

ames=mutate(ames,MS_SubClass= as_factor(MS_SubClass)) 
ames=mutate(ames,MS_Zoning= as_factor(MS_Zoning)) 
ames=mutate(ames,Street= as_factor(Street))
ames=mutate(ames,Alley= as_factor(Alley))
ames=mutate(ames,Lot_Shape= as_factor(Lot_Shape)) #run line from here
ames=mutate(ames,Land_Contour= as_factor(Land_Contour))
ames=mutate(ames,Utilities= as_factor(Utilities))
ames=mutate(ames,Lot_Config= as_factor(Lot_Config))
ames=mutate(ames,Land_Slope= as_factor(Land_Slope))
ames=mutate(ames,Neighborhood= as_factor(Neighborhood))
ames=mutate(ames,Condition_1= as_factor(Condition_1))
ames=mutate(ames,Condition_2= as_factor(Condition_2))
ames=mutate(ames,Bldg_Type= as_factor(Bldg_Type))
ames=mutate(ames,House_Style= as_factor(House_Style))
ames=mutate(ames,Overall_Qual= as_factor(Overall_Qual))
ames=mutate(ames,Overall_Cond= as_factor(Overall_Cond))
ames=mutate(ames,Roof_Style= as_factor(Roof_Style))
ames=mutate(ames,Roof_Matl= as_factor(Roof_Matl))
ames=mutate(ames,Exterior_1st= as_factor(Exterior_1st))
ames=mutate(ames,Exterior_2nd= as_factor(Exterior_2nd))
ames=mutate(ames,Mas_Vnr_Type= as_factor(Mas_Vnr_Type))
ames=mutate(ames,Exter_Qual= as_factor(Exter_Qual))
ames=mutate(ames,Exter_Cond= as_factor(Exter_Cond))
ames=mutate(ames,Foundation= as_factor(Foundation))
ames=mutate(ames,Bsmt_Qual= as_factor(Bsmt_Qual))
ames=mutate(ames,Bsmt_Cond= as_factor(Bsmt_Cond))
ames=mutate(ames,Bsmt_Exposure= as_factor(Bsmt_Exposure))
ames=mutate(ames,BsmtFin_Type_1= as_factor(BsmtFin_Type_1))
ames=mutate(ames,BsmtFin_Type_2= as_factor(BsmtFin_Type_2))
ames=mutate(ames,Heating= as_factor(Heating))
ames=mutate(ames,Heating_QC= as_factor(Heating_QC))
ames=mutate(ames,Central_Air= as_factor(Central_Air))
ames=mutate(ames,Electrical= as_factor(Electrical))
ames=mutate(ames,Kitchen_Qual= as_factor(Kitchen_Qual))
ames=mutate(ames,Functional= as_factor(Functional))
ames=mutate(ames,Fireplace_Qu= as_factor(Fireplace_Qu))
ames=mutate(ames,Garage_Type= as_factor(Garage_Type))
ames=mutate(ames,Garage_Finish= as_factor(Garage_Finish))
ames=mutate(ames,Garage_Qual= as_factor(Garage_Qual))
ames=mutate(ames,Garage_Cond= as_factor(Garage_Cond))
ames=mutate(ames,Paved_Drive= as_factor(Paved_Drive))
ames=mutate(ames,Pool_QC= as_factor(Pool_QC))
ames=mutate(ames,Fence= as_factor(Fence))
ames=mutate(ames,Misc_Feature= as_factor(Misc_Feature))
ames=mutate(ames,Sale_Type= as_factor(Sale_Type))
ames=mutate(ames,Sale_Condition= as_factor(Sale_Condition))
ames=mutate(ames,Above_Median= as_factor(Above_Median))

```

```{r}
set.seed(123) 
ames_split = initial_split(ames, prop = 0.7, strata = Above_Median) #70% in training
train = training(ames_split)
test = testing(ames_split)
```
```{r}
ames_recipe = recipe(Above_Median~.,train)

rf_model = rand_forest() %>% 
  set_engine("ranger", importance = "permutation") %>% #added importance metric
  set_mode("classification")

ames_wflow = 
  workflow() %>% 
  add_model(rf_model) %>% 
  add_recipe(ames_recipe)

set.seed(123)
ames_fit = fit(ames_wflow, train)
```

```{r}
ames_fit
```

```{r}
trainpredrf = predict(ames_fit, train)
head(trainpredrf)
```


```{r}
confusionMatrix(trainpredrf$.pred_class, train$Above_Median, 
                positive = "Yes")
```



